# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('website', models.URLField()),
                ('neighborhood', models.CharField(choices=[('DT', 'Downtown'), ('SE', 'Southeast'), ('RR', 'Outside of Portland'), ('WS', 'Westside'), ('NP', 'North Portland'), ('CK', 'Clackamas')], default='DT', max_length=2)),
            ],
        ),
    ]
