# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleblackbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='email2',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='level',
            field=models.CharField(choices=[('SL', 'Student'), ('JL', 'Junior/Entry Level Professional'), ('PL', 'Mid-Level Professional'), ('EL', 'Expert')], default='PL', max_length=2),
        ),
        migrations.AddField(
            model_name='professional',
            name='phone2',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='website2',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
