# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleblackbookapp', '0004_auto_20160721_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.AddField(
            model_name='professional',
            name='company',
            field=models.ManyToManyField(to='littleblackbookapp.Company'),
        ),
    ]
