# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleblackbookapp', '0005_auto_20160721_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='strengths',
            field=models.ManyToManyField(to='littleblackbookapp.Positive'),
        ),
    ]
