# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleblackbookapp', '0006_auto_20160726_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positive',
            new_name='Strengths',
        ),
    ]
