# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littleblackbookapp', '0007_auto_20160726_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='littleblackbookapp.Professional')),
            ],
        ),
    ]
